# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title: CIBig
description: From sequencing data production to analysis for agriculture and health
#email: bioinfo@wave-center.org
#description: >- # this means to ignore newlines until "baseurl:"
#  The International Certificate in Bioinformatics and Genomics (CIBiG) offers an intensive and concise training aimed at scientists at the intersection of mathematics, biology, and computer science. This training provides a rapid acquisition of essential skills in bioinformatics and genomics. The educational objectives of this training include acquiring the fundamental principles of bioinformatics, understanding sequencing techniques and their application, as well as using bioinformatics tools to automate the collection and management of sequencing data. Additionally, it aims to develop practical skills in the analysis and interpretation of these data. The certificate offers a multidisciplinary training, covering technical and scientific skills such as advanced use of computing clusters, programming, genome sequencing, data reproducibility/open science, and specialization in specific domains of bioinformatics.
#

#include:
#  - _pages
exclude:
  -README.md
  #   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
